plugins/openwriter/xp/Makefile
plugins/openwriter/Makefile
plugins/grammar/linkgrammarwrap/Makefile
plugins/grammar/xp/Makefile
plugins/grammar/Makefile
plugins/wpg/xp/Makefile
plugins/wpg/Makefile
plugins/gimp/xp/Makefile
plugins/gimp/Makefile
plugins/aiksaurus/win/Makefile
plugins/aiksaurus/xp/Makefile
plugins/aiksaurus/aiksaurusgtk3/Makefile
plugins/aiksaurus/Makefile
plugins/command/xp/Makefile
plugins/command/Makefile
plugins/goffice/unix/Makefile
plugins/goffice/Makefile
plugins/sdw/xp/Makefile
plugins/sdw/Makefile
plugins/paint/win/Makefile
plugins/paint/xp/Makefile
plugins/paint/unix/Makefile
plugins/paint/Makefile
plugins/passepartout/xp/Makefile
plugins/passepartout/Makefile
plugins/opendocument/imp/xp/Makefile
plugins/opendocument/imp/Makefile
plugins/opendocument/exp/xp/Makefile
plugins/opendocument/exp/Makefile
plugins/opendocument/common/xp/Makefile
plugins/opendocument/common/Makefile
plugins/opendocument/Makefile
plugins/wml/xp/Makefile
plugins/wml/Makefile
plugins/eml/xp/Makefile
plugins/eml/Makefile
plugins/mht/xp/Makefile
plugins/mht/Makefile
plugins/gdict/unix/Makefile
plugins/gdict/Makefile
plugins/s5/xp/Makefile
plugins/s5/Makefile
plugins/babelfish/xp/Makefile
plugins/babelfish/Makefile
plugins/ots/xp/Makefile
plugins/ots/Makefile
plugins/bmp/xp/Makefile
plugins/bmp/Makefile
plugins/psion/xp/Makefile
plugins/psion/Makefile
plugins/gda/unix/Makefile
plugins/gda/Makefile
plugins/opml/xp/Makefile
plugins/opml/Makefile
plugins/garble/xp/Makefile
plugins/garble/Makefile
plugins/hrtext/xp/Makefile
plugins/hrtext/Makefile
plugins/presentation/xp/Makefile
plugins/presentation/Makefile
plugins/freetranslation/xp/Makefile
plugins/freetranslation/Makefile
plugins/xslfo/xp/Makefile
plugins/xslfo/Makefile
plugins/wordperfect/xp/Makefile
plugins/wordperfect/Makefile
plugins/applix/xp/Makefile
plugins/applix/Makefile
plugins/loadbindings/xp/Makefile
plugins/loadbindings/Makefile
plugins/docbook/xp/Makefile
plugins/docbook/Makefile
plugins/mif/xp/Makefile
plugins/mif/Makefile
plugins/pdf/xp/Makefile
plugins/pdf/Makefile
plugins/google/xp/Makefile
plugins/google/Makefile
plugins/Makefile
plugins/clarisworks/xp/Makefile
plugins/clarisworks/Makefile
plugins/latex/xp/Makefile
plugins/latex/Makefile
plugins/latex/xsltml/Makefile
plugins/t602/xp/Makefile
plugins/t602/Makefile
plugins/mswrite/xp/Makefile
plugins/mswrite/Makefile
plugins/iscii/xp/Makefile
plugins/iscii/Makefile
plugins/openxml/omml_xslt/Makefile
plugins/openxml/imp/xp/Makefile
plugins/openxml/imp/Makefile
plugins/openxml/exp/xp/Makefile
plugins/openxml/exp/Makefile
plugins/openxml/common/xp/Makefile
plugins/openxml/common/Makefile
plugins/openxml/Makefile
plugins/wikipedia/xp/Makefile
plugins/wikipedia/Makefile
plugins/pdb/xp/Makefile
plugins/pdb/Makefile
plugins/urldict/xp/Makefile
plugins/urldict/Makefile
plugins/wmf/xp/Makefile
plugins/wmf/Makefile
plugins/hancom/xp/Makefile
plugins/hancom/Makefile
plugins/epub/dialogs/win/Makefile
plugins/epub/dialogs/xp/Makefile
plugins/epub/dialogs/Makefile
plugins/epub/dialogs/gtk/Makefile
plugins/epub/imp/xp/Makefile
plugins/epub/imp/Makefile
plugins/epub/exp/xp/Makefile
plugins/epub/exp/Makefile
plugins/epub/common/xp/Makefile
plugins/epub/common/Makefile
plugins/epub/Makefile
plugins/kword/xp/Makefile
plugins/kword/Makefile
plugins/rsvg/xp/Makefile
plugins/rsvg/Makefile
